/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCaktoStatusRouteImport } from './routes/api/cakto/status'
import { Route as ApiCaktoWebhookRouteImport } from './routes/api/cakto/webhook'
import { Route as ApiMetaLeadRouteImport } from './routes/api/meta/lead'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCaktoStatusRoute = ApiCaktoStatusRouteImport.update({
  id: '/api/cakto/status',
  path: '/api/cakto/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCaktoWebhookRoute = ApiCaktoWebhookRouteImport.update({
  id: '/api/cakto/webhook',
  path: '/api/cakto/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetaLeadRoute = ApiMetaLeadRouteImport.update({
  id: '/api/meta/lead',
  path: '/api/meta/lead',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/cakto/status': typeof ApiCaktoStatusRoute
  '/api/cakto/webhook': typeof ApiCaktoWebhookRoute
  '/api/meta/lead': typeof ApiMetaLeadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/cakto/status': typeof ApiCaktoStatusRoute
  '/api/cakto/webhook': typeof ApiCaktoWebhookRoute
  '/api/meta/lead': typeof ApiMetaLeadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/cakto/status': typeof ApiCaktoStatusRoute
  '/api/cakto/webhook': typeof ApiCaktoWebhookRoute
  '/api/meta/lead': typeof ApiMetaLeadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/cakto/status' | '/api/cakto/webhook' | '/api/meta/lead'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/cakto/status' | '/api/cakto/webhook' | '/api/meta/lead'
  id: '__root__' | '/' | '/api/cakto/status' | '/api/cakto/webhook' | '/api/meta/lead'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCaktoStatusRoute: typeof ApiCaktoStatusRoute
  ApiCaktoWebhookRoute: typeof ApiCaktoWebhookRoute
  ApiMetaLeadRoute: typeof ApiMetaLeadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cakto/status': {
      id: '/api/cakto/status'
      path: '/api/cakto/status'
      fullPath: '/api/cakto/status'
      preLoaderRoute: typeof ApiCaktoStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cakto/webhook': {
      id: '/api/cakto/webhook'
      path: '/api/cakto/webhook'
      fullPath: '/api/cakto/webhook'
      preLoaderRoute: typeof ApiCaktoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meta/lead': {
      id: '/api/meta/lead'
      path: '/api/meta/lead'
      fullPath: '/api/meta/lead'
      preLoaderRoute: typeof ApiMetaLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCaktoStatusRoute: ApiCaktoStatusRoute,
  ApiCaktoWebhookRoute: ApiCaktoWebhookRoute,
  ApiMetaLeadRoute: ApiMetaLeadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
